import Color from './lib/color.min.js';

const camelCase = (kebabCase) => kebabCase.replace(/-./g, (match) => match[1].toUpperCase());

const rootColorKeys = [
  'black',
  'white',
  'white-on-dark',
  'navy',
  'red',
  'orange',
  'yellow',
  'green',
  'blue',
  'purple',
  'pink',
  'accent',
  'deprecated-accent',
  'secondary-accent'
];

const increments = [3, 5, 10, 15, 20, 30, 40, 50, 60, 70, 80, 85, 90, 95, 100];

export const getCustomTokens = (colors) => {
  const result = {};

  rootColorKeys.forEach((colorNameKebab) => {
    if (!colors[colorNameKebab]) return;

    const key = camelCase(`color-${(colorNameKebab)}`);
    const color = `rgba(${colors[colorNameKebab]}, 1)`;

    result[key] = color;

    const toWhite = new Color(color).range('white', { space: 'srgb' });
    const toBlack = new Color(color).range('black', { space: 'srgb' });
    const format = { format: 'rgba_number', precision: 4 };

    if (colorNameKebab === 'navy') {
      increments.forEach((num) => {
        result[`${key}${num}`] = toWhite((100 - num) / 100).toString(format);
      });
    } else {
      increments.forEach((num) => {
        if (num > 50) {
          result[`${key}${num}`] = toBlack((num * 2 - 100) / 100).toString(format);
        } else {
          result[`${key}${num}`] = toWhite((100 - num * 2) / 100).toString(format);
        }
      });
    }

    increments.forEach((num) => {
      result[`${key}Tint${num}`] = `rgba(${colors[colorNameKebab]}, ${num / 100})`;
    });
  });

  result.colorTransparent = 'rgba(255, 255, 255, 0)';

  return result;
};

/*
import * as colors from './color_tokens.js';

const getDelta = (baseColorRgb, targetColorRgb) => {
  const baseColor = (new Color(baseColorRgb)).to('ictcp');
  const targetColor = (new Color(targetColorRgb)).to('ictcp');

  return {
    'ictcp.i': i => i * (targetColor.ictcp.i / baseColor.ictcp.i),
    'ictcp.ct': ct => ct * (targetColor.ictcp.ct / baseColor.ictcp.ct),
    'ictcp.cp': cp => cp * (targetColor.ictcp.cp / baseColor.ictcp.cp),
    alpha: alpha => alpha * (targetColor.alpha / baseColor.alpha)
  };
};

const deltas = new Map([
  ['colorTransparent', getDelta(colors.colorWhite, colors.colorTransparent)],

  ['colorNavy3', getDelta(colors.colorNavy, colors.colorNavy3)],
  ['colorNavy5', getDelta(colors.colorNavy, colors.colorNavy5)],
  ['colorNavy10', getDelta(colors.colorNavy, colors.colorNavy10)],
  ['colorNavy15', getDelta(colors.colorNavy, colors.colorNavy15)],
  ['colorNavy20', getDelta(colors.colorNavy, colors.colorNavy20)],
  ['colorNavy30', getDelta(colors.colorNavy, colors.colorNavy30)],
  ['colorNavy40', getDelta(colors.colorNavy, colors.colorNavy40)],
  ['colorNavy50', getDelta(colors.colorNavy, colors.colorNavy50)],
  ['colorNavy60', getDelta(colors.colorNavy, colors.colorNavy60)],
  ['colorNavy70', getDelta(colors.colorNavy, colors.colorNavy70)],
  ['colorNavy80', getDelta(colors.colorNavy, colors.colorNavy80)],
  ['colorNavy85', getDelta(colors.colorNavy, colors.colorNavy85)],
  ['colorNavy90', getDelta(colors.colorNavy, colors.colorNavy90)],
  ['colorNavy95', getDelta(colors.colorNavy, colors.colorNavy95)],

  ['colorNavyTint3', getDelta(colors.colorNavy, colors.colorNavyTint3)],
  ['colorNavyTint5', getDelta(colors.colorNavy, colors.colorNavyTint5)],
  ['colorNavyTint10', getDelta(colors.colorNavy, colors.colorNavyTint10)],
  ['colorNavyTint15', getDelta(colors.colorNavy, colors.colorNavyTint15)],
  ['colorNavyTint20', getDelta(colors.colorNavy, colors.colorNavyTint20)],
  ['colorNavyTint30', getDelta(colors.colorNavy, colors.colorNavyTint30)],
  ['colorNavyTint40', getDelta(colors.colorNavy, colors.colorNavyTint40)],
  ['colorNavyTint50', getDelta(colors.colorNavy, colors.colorNavyTint50)],
  ['colorNavyTint60', getDelta(colors.colorNavy, colors.colorNavyTint60)],
  ['colorNavyTint70', getDelta(colors.colorNavy, colors.colorNavyTint70)],
  ['colorNavyTint80', getDelta(colors.colorNavy, colors.colorNavyTint80)],
  ['colorNavyTint85', getDelta(colors.colorNavy, colors.colorNavyTint85)],
  ['colorNavyTint90', getDelta(colors.colorNavy, colors.colorNavyTint90)],
  ['colorNavyTint95', getDelta(colors.colorNavy, colors.colorNavyTint95)],

  ['colorGray3', getDelta(colors.colorBlack, colors.colorGray3)],
  ['colorGray5', getDelta(colors.colorBlack, colors.colorGray5)],
  ['colorGray10', getDelta(colors.colorBlack, colors.colorGray10)],
  ['colorGray15', getDelta(colors.colorBlack, colors.colorGray15)],
  ['colorGray20', getDelta(colors.colorBlack, colors.colorGray20)],
  ['colorGray30', getDelta(colors.colorBlack, colors.colorGray30)],
  ['colorGray40', getDelta(colors.colorBlack, colors.colorGray40)],
  ['colorGray50', getDelta(colors.colorBlack, colors.colorGray50)],
  ['colorGray60', getDelta(colors.colorBlack, colors.colorGray60)],
  ['colorGray70', getDelta(colors.colorBlack, colors.colorGray70)],
  ['colorGray80', getDelta(colors.colorBlack, colors.colorGray80)],
  ['colorGray85', getDelta(colors.colorBlack, colors.colorGray85)],
  ['colorGray90', getDelta(colors.colorBlack, colors.colorGray90)],
  ['colorGray95', getDelta(colors.colorBlack, colors.colorGray95)],

  ['colorBlackTint3', getDelta(colors.colorBlack, colors.colorBlackTint3)],
  ['colorBlackTint5', getDelta(colors.colorBlack, colors.colorBlackTint5)],
  ['colorBlackTint10', getDelta(colors.colorBlack, colors.colorBlackTint10)],
  ['colorBlackTint15', getDelta(colors.colorBlack, colors.colorBlackTint15)],
  ['colorBlackTint20', getDelta(colors.colorBlack, colors.colorBlackTint20)],
  ['colorBlackTint30', getDelta(colors.colorBlack, colors.colorBlackTint30)],
  ['colorBlackTint40', getDelta(colors.colorBlack, colors.colorBlackTint40)],
  ['colorBlackTint50', getDelta(colors.colorBlack, colors.colorBlackTint50)],
  ['colorBlackTint60', getDelta(colors.colorBlack, colors.colorBlackTint60)],
  ['colorBlackTint70', getDelta(colors.colorBlack, colors.colorBlackTint70)],
  ['colorBlackTint80', getDelta(colors.colorBlack, colors.colorBlackTint80)],
  ['colorBlackTint85', getDelta(colors.colorBlack, colors.colorBlackTint85)],
  ['colorBlackTint90', getDelta(colors.colorBlack, colors.colorBlackTint90)],
  ['colorBlackTint95', getDelta(colors.colorBlack, colors.colorBlackTint95)],

  ['colorWhiteTint3', getDelta(colors.colorWhite, colors.colorWhiteTint3)],
  ['colorWhiteTint5', getDelta(colors.colorWhite, colors.colorWhiteTint5)],
  ['colorWhiteTint10', getDelta(colors.colorWhite, colors.colorWhiteTint10)],
  ['colorWhiteTint15', getDelta(colors.colorWhite, colors.colorWhiteTint15)],
  ['colorWhiteTint20', getDelta(colors.colorWhite, colors.colorWhiteTint20)],
  ['colorWhiteTint30', getDelta(colors.colorWhite, colors.colorWhiteTint30)],
  ['colorWhiteTint40', getDelta(colors.colorWhite, colors.colorWhiteTint40)],
  ['colorWhiteTint50', getDelta(colors.colorWhite, colors.colorWhiteTint50)],
  ['colorWhiteTint60', getDelta(colors.colorWhite, colors.colorWhiteTint60)],
  ['colorWhiteTint70', getDelta(colors.colorWhite, colors.colorWhiteTint70)],
  ['colorWhiteTint80', getDelta(colors.colorWhite, colors.colorWhiteTint80)],
  ['colorWhiteTint85', getDelta(colors.colorWhite, colors.colorWhiteTint85)],
  ['colorWhiteTint90', getDelta(colors.colorWhite, colors.colorWhiteTint90)],
  ['colorWhiteTint95', getDelta(colors.colorWhite, colors.colorWhiteTint95)],

  ['colorBlue5', getDelta(colors.colorBlue, colors.colorBlue5)],
  ['colorBlue10', getDelta(colors.colorBlue, colors.colorBlue10)],
  ['colorBlue20', getDelta(colors.colorBlue, colors.colorBlue20)],
  ['colorBlue30', getDelta(colors.colorBlue, colors.colorBlue30)],
  ['colorBlue40', getDelta(colors.colorBlue, colors.colorBlue40)],
  ['colorBlue60', getDelta(colors.colorBlue, colors.colorBlue60)],
  ['colorBlue70', getDelta(colors.colorBlue, colors.colorBlue70)],
  ['colorBlue80', getDelta(colors.colorBlue, colors.colorBlue80)],
  ['colorBlue90', getDelta(colors.colorBlue, colors.colorBlue90)],
  ['colorBlue95', getDelta(colors.colorBlue, colors.colorBlue95)],

  ['colorBlueTint5', getDelta(colors.colorBlue, colors.colorBlueTint5)],
  ['colorBlueTint10', getDelta(colors.colorBlue, colors.colorBlueTint10)],
  ['colorBlueTint20', getDelta(colors.colorBlue, colors.colorBlueTint20)],
  ['colorBlueTint30', getDelta(colors.colorBlue, colors.colorBlueTint30)],
  ['colorBlueTint40', getDelta(colors.colorBlue, colors.colorBlueTint40)],
  ['colorBlueTint50', getDelta(colors.colorBlue, colors.colorBlueTint50)],
  ['colorBlueTint60', getDelta(colors.colorBlue, colors.colorBlueTint60)],
  ['colorBlueTint70', getDelta(colors.colorBlue, colors.colorBlueTint70)],
  ['colorBlueTint80', getDelta(colors.colorBlue, colors.colorBlueTint80)],
  ['colorBlueTint90', getDelta(colors.colorBlue, colors.colorBlueTint90)],
  ['colorBlueTint95', getDelta(colors.colorBlue, colors.colorBlueTint95)],

  ['colorPurple5', getDelta(colors.colorPurple, colors.colorPurple5)],
  ['colorPurple10', getDelta(colors.colorPurple, colors.colorPurple10)],
  ['colorPurple20', getDelta(colors.colorPurple, colors.colorPurple20)],
  ['colorPurple30', getDelta(colors.colorPurple, colors.colorPurple30)],
  ['colorPurple40', getDelta(colors.colorPurple, colors.colorPurple40)],
  ['colorPurple60', getDelta(colors.colorPurple, colors.colorPurple60)],
  ['colorPurple70', getDelta(colors.colorPurple, colors.colorPurple70)],
  ['colorPurple80', getDelta(colors.colorPurple, colors.colorPurple80)],
  ['colorPurple90', getDelta(colors.colorPurple, colors.colorPurple90)],
  ['colorPurple95', getDelta(colors.colorPurple, colors.colorPurple95)],

  ['colorPurpleTint5', getDelta(colors.colorPurple, colors.colorPurpleTint5)],
  ['colorPurpleTint10', getDelta(colors.colorPurple, colors.colorPurpleTint10)],
  ['colorPurpleTint20', getDelta(colors.colorPurple, colors.colorPurpleTint20)],
  ['colorPurpleTint30', getDelta(colors.colorPurple, colors.colorPurpleTint30)],
  ['colorPurpleTint40', getDelta(colors.colorPurple, colors.colorPurpleTint40)],
  ['colorPurpleTint50', getDelta(colors.colorPurple, colors.colorPurpleTint50)],
  ['colorPurpleTint60', getDelta(colors.colorPurple, colors.colorPurpleTint60)],
  ['colorPurpleTint70', getDelta(colors.colorPurple, colors.colorPurpleTint70)],
  ['colorPurpleTint80', getDelta(colors.colorPurple, colors.colorPurpleTint80)],
  ['colorPurpleTint90', getDelta(colors.colorPurple, colors.colorPurpleTint90)],
  ['colorPurpleTint95', getDelta(colors.colorPurple, colors.colorPurpleTint95)],

  ['colorPink5', getDelta(colors.colorPink, colors.colorPink5)],
  ['colorPink10', getDelta(colors.colorPink, colors.colorPink10)],
  ['colorPink20', getDelta(colors.colorPink, colors.colorPink20)],
  ['colorPink30', getDelta(colors.colorPink, colors.colorPink30)],
  ['colorPink40', getDelta(colors.colorPink, colors.colorPink40)],
  ['colorPink60', getDelta(colors.colorPink, colors.colorPink60)],
  ['colorPink70', getDelta(colors.colorPink, colors.colorPink70)],
  ['colorPink80', getDelta(colors.colorPink, colors.colorPink80)],
  ['colorPink90', getDelta(colors.colorPink, colors.colorPink90)],
  ['colorPink95', getDelta(colors.colorPink, colors.colorPink95)],

  ['colorPinkTint5', getDelta(colors.colorPink, colors.colorPinkTint5)],
  ['colorPinkTint10', getDelta(colors.colorPink, colors.colorPinkTint10)],
  ['colorPinkTint20', getDelta(colors.colorPink, colors.colorPinkTint20)],
  ['colorPinkTint30', getDelta(colors.colorPink, colors.colorPinkTint30)],
  ['colorPinkTint40', getDelta(colors.colorPink, colors.colorPinkTint40)],
  ['colorPinkTint50', getDelta(colors.colorPink, colors.colorPinkTint50)],
  ['colorPinkTint60', getDelta(colors.colorPink, colors.colorPinkTint60)],
  ['colorPinkTint70', getDelta(colors.colorPink, colors.colorPinkTint70)],
  ['colorPinkTint80', getDelta(colors.colorPink, colors.colorPinkTint80)],
  ['colorPinkTint90', getDelta(colors.colorPink, colors.colorPinkTint90)],
  ['colorPinkTint95', getDelta(colors.colorPink, colors.colorPinkTint95)],

  ['colorRed5', getDelta(colors.colorRed, colors.colorRed5)],
  ['colorRed10', getDelta(colors.colorRed, colors.colorRed10)],
  ['colorRed20', getDelta(colors.colorRed, colors.colorRed20)],
  ['colorRed30', getDelta(colors.colorRed, colors.colorRed30)],
  ['colorRed40', getDelta(colors.colorRed, colors.colorRed40)],
  ['colorRed60', getDelta(colors.colorRed, colors.colorRed60)],
  ['colorRed70', getDelta(colors.colorRed, colors.colorRed70)],
  ['colorRed80', getDelta(colors.colorRed, colors.colorRed80)],
  ['colorRed90', getDelta(colors.colorRed, colors.colorRed90)],
  ['colorRed95', getDelta(colors.colorRed, colors.colorRed95)],

  ['colorRedTint5', getDelta(colors.colorRed, colors.colorRedTint5)],
  ['colorRedTint10', getDelta(colors.colorRed, colors.colorRedTint10)],
  ['colorRedTint20', getDelta(colors.colorRed, colors.colorRedTint20)],
  ['colorRedTint30', getDelta(colors.colorRed, colors.colorRedTint30)],
  ['colorRedTint40', getDelta(colors.colorRed, colors.colorRedTint40)],
  ['colorRedTint50', getDelta(colors.colorRed, colors.colorRedTint50)],
  ['colorRedTint60', getDelta(colors.colorRed, colors.colorRedTint60)],
  ['colorRedTint70', getDelta(colors.colorRed, colors.colorRedTint70)],
  ['colorRedTint80', getDelta(colors.colorRed, colors.colorRedTint80)],
  ['colorRedTint90', getDelta(colors.colorRed, colors.colorRedTint90)],
  ['colorRedTint95', getDelta(colors.colorRed, colors.colorRedTint95)],

  ['colorOrange5', getDelta(colors.colorOrange, colors.colorOrange5)],
  ['colorOrange10', getDelta(colors.colorOrange, colors.colorOrange10)],
  ['colorOrange20', getDelta(colors.colorOrange, colors.colorOrange20)],
  ['colorOrange30', getDelta(colors.colorOrange, colors.colorOrange30)],
  ['colorOrange40', getDelta(colors.colorOrange, colors.colorOrange40)],
  ['colorOrange60', getDelta(colors.colorOrange, colors.colorOrange60)],
  ['colorOrange70', getDelta(colors.colorOrange, colors.colorOrange70)],
  ['colorOrange80', getDelta(colors.colorOrange, colors.colorOrange80)],
  ['colorOrange90', getDelta(colors.colorOrange, colors.colorOrange90)],
  ['colorOrange95', getDelta(colors.colorOrange, colors.colorOrange95)],

  ['colorOrangeTint5', getDelta(colors.colorOrange, colors.colorOrangeTint5)],
  ['colorOrangeTint10', getDelta(colors.colorOrange, colors.colorOrangeTint10)],
  ['colorOrangeTint20', getDelta(colors.colorOrange, colors.colorOrangeTint20)],
  ['colorOrangeTint30', getDelta(colors.colorOrange, colors.colorOrangeTint30)],
  ['colorOrangeTint40', getDelta(colors.colorOrange, colors.colorOrangeTint40)],
  ['colorOrangeTint50', getDelta(colors.colorOrange, colors.colorOrangeTint50)],
  ['colorOrangeTint60', getDelta(colors.colorOrange, colors.colorOrangeTint60)],
  ['colorOrangeTint70', getDelta(colors.colorOrange, colors.colorOrangeTint70)],
  ['colorOrangeTint80', getDelta(colors.colorOrange, colors.colorOrangeTint80)],
  ['colorOrangeTint90', getDelta(colors.colorOrange, colors.colorOrangeTint90)],
  ['colorOrangeTint95', getDelta(colors.colorOrange, colors.colorOrangeTint95)],

  ['colorYellow5', getDelta(colors.colorYellow, colors.colorYellow5)],
  ['colorYellow10', getDelta(colors.colorYellow, colors.colorYellow10)],
  ['colorYellow20', getDelta(colors.colorYellow, colors.colorYellow20)],
  ['colorYellow30', getDelta(colors.colorYellow, colors.colorYellow30)],
  ['colorYellow40', getDelta(colors.colorYellow, colors.colorYellow40)],
  ['colorYellow60', getDelta(colors.colorYellow, colors.colorYellow60)],
  ['colorYellow70', getDelta(colors.colorYellow, colors.colorYellow70)],
  ['colorYellow80', getDelta(colors.colorYellow, colors.colorYellow80)],
  ['colorYellow90', getDelta(colors.colorYellow, colors.colorYellow90)],
  ['colorYellow95', getDelta(colors.colorYellow, colors.colorYellow95)],

  ['colorYellowTint5', getDelta(colors.colorYellow, colors.colorYellowTint5)],
  ['colorYellowTint10', getDelta(colors.colorYellow, colors.colorYellowTint10)],
  ['colorYellowTint20', getDelta(colors.colorYellow, colors.colorYellowTint20)],
  ['colorYellowTint30', getDelta(colors.colorYellow, colors.colorYellowTint30)],
  ['colorYellowTint40', getDelta(colors.colorYellow, colors.colorYellowTint40)],
  ['colorYellowTint50', getDelta(colors.colorYellow, colors.colorYellowTint50)],
  ['colorYellowTint60', getDelta(colors.colorYellow, colors.colorYellowTint60)],
  ['colorYellowTint70', getDelta(colors.colorYellow, colors.colorYellowTint70)],
  ['colorYellowTint80', getDelta(colors.colorYellow, colors.colorYellowTint80)],
  ['colorYellowTint90', getDelta(colors.colorYellow, colors.colorYellowTint90)],
  ['colorYellowTint95', getDelta(colors.colorYellow, colors.colorYellowTint95)],

  ['colorGreen5', getDelta(colors.colorGreen, colors.colorGreen5)],
  ['colorGreen10', getDelta(colors.colorGreen, colors.colorGreen10)],
  ['colorGreen20', getDelta(colors.colorGreen, colors.colorGreen20)],
  ['colorGreen30', getDelta(colors.colorGreen, colors.colorGreen30)],
  ['colorGreen40', getDelta(colors.colorGreen, colors.colorGreen40)],
  ['colorGreen60', getDelta(colors.colorGreen, colors.colorGreen60)],
  ['colorGreen70', getDelta(colors.colorGreen, colors.colorGreen70)],
  ['colorGreen80', getDelta(colors.colorGreen, colors.colorGreen80)],
  ['colorGreen90', getDelta(colors.colorGreen, colors.colorGreen90)],
  ['colorGreen95', getDelta(colors.colorGreen, colors.colorGreen95)],

  ['colorGreenTint5', getDelta(colors.colorGreen, colors.colorGreenTint5)],
  ['colorGreenTint10', getDelta(colors.colorGreen, colors.colorGreenTint10)],
  ['colorGreenTint20', getDelta(colors.colorGreen, colors.colorGreenTint20)],
  ['colorGreenTint30', getDelta(colors.colorGreen, colors.colorGreenTint30)],
  ['colorGreenTint40', getDelta(colors.colorGreen, colors.colorGreenTint40)],
  ['colorGreenTint50', getDelta(colors.colorGreen, colors.colorGreenTint50)],
  ['colorGreenTint60', getDelta(colors.colorGreen, colors.colorGreenTint60)],
  ['colorGreenTint70', getDelta(colors.colorGreen, colors.colorGreenTint70)],
  ['colorGreenTint80', getDelta(colors.colorGreen, colors.colorGreenTint80)],
  ['colorGreenTint90', getDelta(colors.colorGreen, colors.colorGreenTint90)],
  ['colorGreenTint95', getDelta(colors.colorGreen, colors.colorGreenTint95)],

  ['colorRainbow2', getDelta(colors.colorGreen, colors.colorRainbow2)],
  ['colorRainbow5', getDelta(colors.colorOrange, colors.colorRainbow5)],
  ['colorRainbow7', getDelta(colors.colorRed, colors.colorRainbow7)],
  ['colorRainbow9', getDelta(colors.colorPink, colors.colorRainbow9)]
]);

export const getCustomTokens = ({
  colorNavy,
  colorBlue,
  colorPurple,
  colorPink,
  colorRed,
  colorOrange,
  colorYellow,
  colorGreen,
  colorBlack,
  colorWhite,
  colorWhiteOnDark,
  colorAccent
}) => {
  const baseNavy = new Color(colorNavy);
  const baseBlue = new Color(colorBlue);
  const basePurple = new Color(colorPurple);
  const basePink = new Color(colorPink);
  const baseRed = new Color(colorRed);
  const baseOrange = new Color(colorOrange);
  const baseYellow = new Color(colorYellow);
  const baseGreen = new Color(colorGreen);
  const baseBlack = new Color(colorBlack);
  const baseWhite = new Color(colorWhite);
  const baseWhiteOnDark = new Color(colorWhiteOnDark);
  const baseAccent = new Color(colorAccent);

  return {
    colorNavy,
    colorBlue,
    colorPurple,
    colorPink,
    colorRed,
    colorOrange,
    colorYellow,
    colorGreen,
    colorBlack,
    colorWhite,
    colorWhiteOnDark,
    colorAccent,

    colorTransparent: baseWhite.set(deltas.get('colorTransparent')).to('srgb').toString(),

    colorNavy3: baseNavy.set(deltas.get('colorNavy3')).to('srgb').toString(),
    colorNavy5: baseNavy.set(deltas.get('colorNavy5')).to('srgb').toString(),
    colorNavy10: baseNavy.set(deltas.get('colorNavy10')).to('srgb').toString(),
    colorNavy15: baseNavy.set(deltas.get('colorNavy15')).to('srgb').toString(),
    colorNavy20: baseNavy.set(deltas.get('colorNavy20')).to('srgb').toString(),
    colorNavy30: baseNavy.set(deltas.get('colorNavy30')).to('srgb').toString(),
    colorNavy40: baseNavy.set(deltas.get('colorNavy40')).to('srgb').toString(),
    colorNavy50: baseNavy.set(deltas.get('colorNavy50')).to('srgb').toString(),
    colorNavy60: baseNavy.set(deltas.get('colorNavy60')).to('srgb').toString(),
    colorNavy70: baseNavy.set(deltas.get('colorNavy70')).to('srgb').toString(),
    colorNavy80: baseNavy.set(deltas.get('colorNavy80')).to('srgb').toString(),
    colorNavy85: baseNavy.set(deltas.get('colorNavy85')).to('srgb').toString(),
    colorNavy90: baseNavy.set(deltas.get('colorNavy90')).to('srgb').toString(),
    colorNavy95: baseNavy.set(deltas.get('colorNavy95')).to('srgb').toString(),
    colorNavy100: colorNavy,

    colorNavyTint3: baseNavy.set(deltas.get('colorNavyTint3')).to('srgb').toString(),
    colorNavyTint5: baseNavy.set(deltas.get('colorNavyTint5')).to('srgb').toString(),
    colorNavyTint10: baseNavy.set(deltas.get('colorNavyTint10')).to('srgb').toString(),
    colorNavyTint15: baseNavy.set(deltas.get('colorNavyTint15')).to('srgb').toString(),
    colorNavyTint20: baseNavy.set(deltas.get('colorNavyTint20')).to('srgb').toString(),
    colorNavyTint30: baseNavy.set(deltas.get('colorNavyTint30')).to('srgb').toString(),
    colorNavyTint40: baseNavy.set(deltas.get('colorNavyTint40')).to('srgb').toString(),
    colorNavyTint50: baseNavy.set(deltas.get('colorNavyTint50')).to('srgb').toString(),
    colorNavyTint60: baseNavy.set(deltas.get('colorNavyTint60')).to('srgb').toString(),
    colorNavyTint70: baseNavy.set(deltas.get('colorNavyTint70')).to('srgb').toString(),
    colorNavyTint80: baseNavy.set(deltas.get('colorNavyTint80')).to('srgb').toString(),
    colorNavyTint85: baseNavy.set(deltas.get('colorNavyTint85')).to('srgb').toString(),
    colorNavyTint90: baseNavy.set(deltas.get('colorNavyTint90')).to('srgb').toString(),
    colorNavyTint95: baseNavy.set(deltas.get('colorNavyTint95')).to('srgb').toString(),

    colorGray3: baseBlack.set(deltas.get('colorGray3')).to('srgb').toString(),
    colorGray5: baseBlack.set(deltas.get('colorGray5')).to('srgb').toString(),
    colorGray10: baseBlack.set(deltas.get('colorGray10')).to('srgb').toString(),
    colorGray15: baseBlack.set(deltas.get('colorGray15')).to('srgb').toString(),
    colorGray20: baseBlack.set(deltas.get('colorGray20')).to('srgb').toString(),
    colorGray30: baseBlack.set(deltas.get('colorGray30')).to('srgb').toString(),
    colorGray40: baseBlack.set(deltas.get('colorGray40')).to('srgb').toString(),
    colorGray50: baseBlack.set(deltas.get('colorGray50')).to('srgb').toString(),
    colorGray60: baseBlack.set(deltas.get('colorGray60')).to('srgb').toString(),
    colorGray70: baseBlack.set(deltas.get('colorGray70')).to('srgb').toString(),
    colorGray80: baseBlack.set(deltas.get('colorGray80')).to('srgb').toString(),
    colorGray85: baseBlack.set(deltas.get('colorGray85')).to('srgb').toString(),
    colorGray90: baseBlack.set(deltas.get('colorGray90')).to('srgb').toString(),
    colorGray95: baseBlack.set(deltas.get('colorGray95')).to('srgb').toString(),
    colorGray100: colorBlack,

    colorBlackTint3: baseBlack.set(deltas.get('colorBlackTint3')).to('srgb').toString(),
    colorBlackTint5: baseBlack.set(deltas.get('colorBlackTint5')).to('srgb').toString(),
    colorBlackTint10: baseBlack.set(deltas.get('colorBlackTint10')).to('srgb').toString(),
    colorBlackTint15: baseBlack.set(deltas.get('colorBlackTint15')).to('srgb').toString(),
    colorBlackTint20: baseBlack.set(deltas.get('colorBlackTint20')).to('srgb').toString(),
    colorBlackTint30: baseBlack.set(deltas.get('colorBlackTint30')).to('srgb').toString(),
    colorBlackTint40: baseBlack.set(deltas.get('colorBlackTint40')).to('srgb').toString(),
    colorBlackTint50: baseBlack.set(deltas.get('colorBlackTint50')).to('srgb').toString(),
    colorBlackTint60: baseBlack.set(deltas.get('colorBlackTint60')).to('srgb').toString(),
    colorBlackTint70: baseBlack.set(deltas.get('colorBlackTint70')).to('srgb').toString(),
    colorBlackTint80: baseBlack.set(deltas.get('colorBlackTint80')).to('srgb').toString(),
    colorBlackTint85: baseBlack.set(deltas.get('colorBlackTint85')).to('srgb').toString(),
    colorBlackTint90: baseBlack.set(deltas.get('colorBlackTint90')).to('srgb').toString(),
    colorBlackTint95: baseBlack.set(deltas.get('colorBlackTint95')).to('srgb').toString(),

    colorWhiteTint3: baseWhite.set(deltas.get('colorWhiteTint3')).to('srgb').toString(),
    colorWhiteTint5: baseWhite.set(deltas.get('colorWhiteTint5')).to('srgb').toString(),
    colorWhiteTint10: baseWhite.set(deltas.get('colorWhiteTint10')).to('srgb').toString(),
    colorWhiteTint15: baseWhite.set(deltas.get('colorWhiteTint15')).to('srgb').toString(),
    colorWhiteTint20: baseWhite.set(deltas.get('colorWhiteTint20')).to('srgb').toString(),
    colorWhiteTint30: baseWhite.set(deltas.get('colorWhiteTint30')).to('srgb').toString(),
    colorWhiteTint40: baseWhite.set(deltas.get('colorWhiteTint40')).to('srgb').toString(),
    colorWhiteTint50: baseWhite.set(deltas.get('colorWhiteTint50')).to('srgb').toString(),
    colorWhiteTint60: baseWhite.set(deltas.get('colorWhiteTint60')).to('srgb').toString(),
    colorWhiteTint70: baseWhite.set(deltas.get('colorWhiteTint70')).to('srgb').toString(),
    colorWhiteTint80: baseWhite.set(deltas.get('colorWhiteTint80')).to('srgb').toString(),
    colorWhiteTint85: baseWhite.set(deltas.get('colorWhiteTint85')).to('srgb').toString(),
    colorWhiteTint90: baseWhite.set(deltas.get('colorWhiteTint90')).to('srgb').toString(),
    colorWhiteTint95: baseWhite.set(deltas.get('colorWhiteTint95')).to('srgb').toString(),

    colorWhiteOnDarkTint3: baseWhiteOnDark.set(deltas.get('colorWhiteTint3')).to('srgb').toString(),
    colorWhiteOnDarkTint5: baseWhiteOnDark.set(deltas.get('colorWhiteTint5')).to('srgb').toString(),
    colorWhiteOnDarkTint10: baseWhiteOnDark.set(deltas.get('colorWhiteTint10')).to('srgb').toString(),
    colorWhiteOnDarkTint15: baseWhiteOnDark.set(deltas.get('colorWhiteTint15')).to('srgb').toString(),
    colorWhiteOnDarkTint20: baseWhiteOnDark.set(deltas.get('colorWhiteTint20')).to('srgb').toString(),
    colorWhiteOnDarkTint30: baseWhiteOnDark.set(deltas.get('colorWhiteTint30')).to('srgb').toString(),
    colorWhiteOnDarkTint40: baseWhiteOnDark.set(deltas.get('colorWhiteTint40')).to('srgb').toString(),
    colorWhiteOnDarkTint50: baseWhiteOnDark.set(deltas.get('colorWhiteTint50')).to('srgb').toString(),
    colorWhiteOnDarkTint60: baseWhiteOnDark.set(deltas.get('colorWhiteTint60')).to('srgb').toString(),
    colorWhiteOnDarkTint70: baseWhiteOnDark.set(deltas.get('colorWhiteTint70')).to('srgb').toString(),
    colorWhiteOnDarkTint80: baseWhiteOnDark.set(deltas.get('colorWhiteTint80')).to('srgb').toString(),
    colorWhiteOnDarkTint85: baseWhiteOnDark.set(deltas.get('colorWhiteTint85')).to('srgb').toString(),
    colorWhiteOnDarkTint90: baseWhiteOnDark.set(deltas.get('colorWhiteTint90')).to('srgb').toString(),
    colorWhiteOnDarkTint95: baseWhiteOnDark.set(deltas.get('colorWhiteTint95')).to('srgb').toString(),

    colorBlue5: baseBlue.set(deltas.get('colorBlue5')).to('srgb').toString(),
    colorBlue10: baseBlue.set(deltas.get('colorBlue10')).to('srgb').toString(),
    colorBlue20: baseBlue.set(deltas.get('colorBlue20')).to('srgb').toString(),
    colorBlue30: baseBlue.set(deltas.get('colorBlue30')).to('srgb').toString(),
    colorBlue40: baseBlue.set(deltas.get('colorBlue40')).to('srgb').toString(),
    colorBlue50: colorBlue,
    colorBlue60: baseBlue.set(deltas.get('colorBlue60')).to('srgb').toString(),
    colorBlue70: baseBlue.set(deltas.get('colorBlue70')).to('srgb').toString(),
    colorBlue80: baseBlue.set(deltas.get('colorBlue80')).to('srgb').toString(),
    colorBlue90: baseBlue.set(deltas.get('colorBlue90')).to('srgb').toString(),
    colorBlue95: baseBlue.set(deltas.get('colorBlue95')).to('srgb').toString(),

    colorBlueTint5: baseBlue.set(deltas.get('colorBlueTint5')).to('srgb').toString(),
    colorBlueTint10: baseBlue.set(deltas.get('colorBlueTint10')).to('srgb').toString(),
    colorBlueTint20: baseBlue.set(deltas.get('colorBlueTint20')).to('srgb').toString(),
    colorBlueTint30: baseBlue.set(deltas.get('colorBlueTint30')).to('srgb').toString(),
    colorBlueTint40: baseBlue.set(deltas.get('colorBlueTint40')).to('srgb').toString(),
    colorBlueTint50: baseBlue.set(deltas.get('colorBlueTint50')).to('srgb').toString(),
    colorBlueTint60: baseBlue.set(deltas.get('colorBlueTint60')).to('srgb').toString(),
    colorBlueTint70: baseBlue.set(deltas.get('colorBlueTint70')).to('srgb').toString(),
    colorBlueTint80: baseBlue.set(deltas.get('colorBlueTint80')).to('srgb').toString(),
    colorBlueTint90: baseBlue.set(deltas.get('colorBlueTint90')).to('srgb').toString(),
    colorBlueTint95: baseBlue.set(deltas.get('colorBlueTint95')).to('srgb').toString(),

    colorAccent5: baseAccent.set(deltas.get('colorBlue5')).to('srgb').toString(),
    colorAccent10: baseAccent.set(deltas.get('colorBlue10')).to('srgb').toString(),
    colorAccent20: baseAccent.set(deltas.get('colorBlue20')).to('srgb').toString(),
    colorAccent30: baseAccent.set(deltas.get('colorBlue30')).to('srgb').toString(),
    colorAccent40: baseAccent.set(deltas.get('colorBlue40')).to('srgb').toString(),
    colorAccent50: colorAccent,
    colorAccent60: baseAccent.set(deltas.get('colorBlue60')).to('srgb').toString(),
    colorAccent70: baseAccent.set(deltas.get('colorBlue70')).to('srgb').toString(),
    colorAccent80: baseAccent.set(deltas.get('colorBlue80')).to('srgb').toString(),
    colorAccent90: baseAccent.set(deltas.get('colorBlue90')).to('srgb').toString(),
    colorAccent95: baseAccent.set(deltas.get('colorBlue95')).to('srgb').toString(),

    colorAccentTint5: baseAccent.set(deltas.get('colorBlueTint5')).to('srgb').toString(),
    colorAccentTint10: baseAccent.set(deltas.get('colorBlueTint10')).to('srgb').toString(),
    colorAccentTint20: baseAccent.set(deltas.get('colorBlueTint20')).to('srgb').toString(),
    colorAccentTint30: baseAccent.set(deltas.get('colorBlueTint30')).to('srgb').toString(),
    colorAccentTint40: baseAccent.set(deltas.get('colorBlueTint40')).to('srgb').toString(),
    colorAccentTint50: baseAccent.set(deltas.get('colorBlueTint50')).to('srgb').toString(),
    colorAccentTint60: baseAccent.set(deltas.get('colorBlueTint60')).to('srgb').toString(),
    colorAccentTint70: baseAccent.set(deltas.get('colorBlueTint70')).to('srgb').toString(),
    colorAccentTint80: baseAccent.set(deltas.get('colorBlueTint80')).to('srgb').toString(),
    colorAccentTint90: baseAccent.set(deltas.get('colorBlueTint90')).to('srgb').toString(),
    colorAccentTint95: baseAccent.set(deltas.get('colorBlueTint95')).to('srgb').toString(),

    colorPurple5: basePurple.set(deltas.get('colorPurple5')).to('srgb').toString(),
    colorPurple10: basePurple.set(deltas.get('colorPurple10')).to('srgb').toString(),
    colorPurple20: basePurple.set(deltas.get('colorPurple20')).to('srgb').toString(),
    colorPurple30: basePurple.set(deltas.get('colorPurple30')).to('srgb').toString(),
    colorPurple40: basePurple.set(deltas.get('colorPurple40')).to('srgb').toString(),
    colorPurple50: colorPurple,
    colorPurple60: basePurple.set(deltas.get('colorPurple60')).to('srgb').toString(),
    colorPurple70: basePurple.set(deltas.get('colorPurple70')).to('srgb').toString(),
    colorPurple80: basePurple.set(deltas.get('colorPurple80')).to('srgb').toString(),
    colorPurple90: basePurple.set(deltas.get('colorPurple90')).to('srgb').toString(),
    colorPurple95: basePurple.set(deltas.get('colorPurple95')).to('srgb').toString(),

    colorPurpleTint5: basePurple.set(deltas.get('colorPurpleTint5')).to('srgb').toString(),
    colorPurpleTint10: basePurple.set(deltas.get('colorPurpleTint10')).to('srgb').toString(),
    colorPurpleTint20: basePurple.set(deltas.get('colorPurpleTint20')).to('srgb').toString(),
    colorPurpleTint30: basePurple.set(deltas.get('colorPurpleTint30')).to('srgb').toString(),
    colorPurpleTint40: basePurple.set(deltas.get('colorPurpleTint40')).to('srgb').toString(),
    colorPurpleTint50: basePurple.set(deltas.get('colorPurpleTint50')).to('srgb').toString(),
    colorPurpleTint60: basePurple.set(deltas.get('colorPurpleTint60')).to('srgb').toString(),
    colorPurpleTint70: basePurple.set(deltas.get('colorPurpleTint70')).to('srgb').toString(),
    colorPurpleTint80: basePurple.set(deltas.get('colorPurpleTint80')).to('srgb').toString(),
    colorPurpleTint90: basePurple.set(deltas.get('colorPurpleTint90')).to('srgb').toString(),
    colorPurpleTint95: basePurple.set(deltas.get('colorPurpleTint95')).to('srgb').toString(),

    colorPink5: basePink.set(deltas.get('colorPink5')).to('srgb').toString(),
    colorPink10: basePink.set(deltas.get('colorPink10')).to('srgb').toString(),
    colorPink20: basePink.set(deltas.get('colorPink20')).to('srgb').toString(),
    colorPink30: basePink.set(deltas.get('colorPink30')).to('srgb').toString(),
    colorPink40: basePink.set(deltas.get('colorPink40')).to('srgb').toString(),
    colorPink50: colorPink,
    colorPink60: basePink.set(deltas.get('colorPink60')).to('srgb').toString(),
    colorPink70: basePink.set(deltas.get('colorPink70')).to('srgb').toString(),
    colorPink80: basePink.set(deltas.get('colorPink80')).to('srgb').toString(),
    colorPink90: basePink.set(deltas.get('colorPink90')).to('srgb').toString(),
    colorPink95: basePink.set(deltas.get('colorPink95')).to('srgb').toString(),

    colorPinkTint5: basePink.set(deltas.get('colorPinkTint5')).to('srgb').toString(),
    colorPinkTint10: basePink.set(deltas.get('colorPinkTint10')).to('srgb').toString(),
    colorPinkTint20: basePink.set(deltas.get('colorPinkTint20')).to('srgb').toString(),
    colorPinkTint30: basePink.set(deltas.get('colorPinkTint30')).to('srgb').toString(),
    colorPinkTint40: basePink.set(deltas.get('colorPinkTint40')).to('srgb').toString(),
    colorPinkTint50: basePink.set(deltas.get('colorPinkTint50')).to('srgb').toString(),
    colorPinkTint60: basePink.set(deltas.get('colorPinkTint60')).to('srgb').toString(),
    colorPinkTint70: basePink.set(deltas.get('colorPinkTint70')).to('srgb').toString(),
    colorPinkTint80: basePink.set(deltas.get('colorPinkTint80')).to('srgb').toString(),
    colorPinkTint90: basePink.set(deltas.get('colorPinkTint90')).to('srgb').toString(),
    colorPinkTint95: basePink.set(deltas.get('colorPinkTint95')).to('srgb').toString(),

    colorRed5: baseRed.set(deltas.get('colorRed5')).to('srgb').toString(),
    colorRed10: baseRed.set(deltas.get('colorRed10')).to('srgb').toString(),
    colorRed20: baseRed.set(deltas.get('colorRed20')).to('srgb').toString(),
    colorRed30: baseRed.set(deltas.get('colorRed30')).to('srgb').toString(),
    colorRed40: baseRed.set(deltas.get('colorRed40')).to('srgb').toString(),
    colorRed50: colorRed,
    colorRed60: baseRed.set(deltas.get('colorRed60')).to('srgb').toString(),
    colorRed70: baseRed.set(deltas.get('colorRed70')).to('srgb').toString(),
    colorRed80: baseRed.set(deltas.get('colorRed80')).to('srgb').toString(),
    colorRed90: baseRed.set(deltas.get('colorRed90')).to('srgb').toString(),
    colorRed95: baseRed.set(deltas.get('colorRed95')).to('srgb').toString(),

    colorRedTint5: baseRed.set(deltas.get('colorRedTint5')).to('srgb').toString(),
    colorRedTint10: baseRed.set(deltas.get('colorRedTint10')).to('srgb').toString(),
    colorRedTint20: baseRed.set(deltas.get('colorRedTint20')).to('srgb').toString(),
    colorRedTint30: baseRed.set(deltas.get('colorRedTint30')).to('srgb').toString(),
    colorRedTint40: baseRed.set(deltas.get('colorRedTint40')).to('srgb').toString(),
    colorRedTint50: baseRed.set(deltas.get('colorRedTint50')).to('srgb').toString(),
    colorRedTint60: baseRed.set(deltas.get('colorRedTint60')).to('srgb').toString(),
    colorRedTint70: baseRed.set(deltas.get('colorRedTint70')).to('srgb').toString(),
    colorRedTint80: baseRed.set(deltas.get('colorRedTint80')).to('srgb').toString(),
    colorRedTint90: baseRed.set(deltas.get('colorRedTint90')).to('srgb').toString(),
    colorRedTint95: baseRed.set(deltas.get('colorRedTint95')).to('srgb').toString(),

    colorOrange5: baseOrange.set(deltas.get('colorOrange5')).to('srgb').toString(),
    colorOrange10: baseOrange.set(deltas.get('colorOrange10')).to('srgb').toString(),
    colorOrange20: baseOrange.set(deltas.get('colorOrange20')).to('srgb').toString(),
    colorOrange30: baseOrange.set(deltas.get('colorOrange30')).to('srgb').toString(),
    colorOrange40: baseOrange.set(deltas.get('colorOrange40')).to('srgb').toString(),
    colorOrange50: colorOrange,
    colorOrange60: baseOrange.set(deltas.get('colorOrange60')).to('srgb').toString(),
    colorOrange70: baseOrange.set(deltas.get('colorOrange70')).to('srgb').toString(),
    colorOrange80: baseOrange.set(deltas.get('colorOrange80')).to('srgb').toString(),
    colorOrange90: baseOrange.set(deltas.get('colorOrange90')).to('srgb').toString(),
    colorOrange95: baseOrange.set(deltas.get('colorOrange95')).to('srgb').toString(),

    colorOrangeTint5: baseOrange.set(deltas.get('colorOrangeTint5')).to('srgb').toString(),
    colorOrangeTint10: baseOrange.set(deltas.get('colorOrangeTint10')).to('srgb').toString(),
    colorOrangeTint20: baseOrange.set(deltas.get('colorOrangeTint20')).to('srgb').toString(),
    colorOrangeTint30: baseOrange.set(deltas.get('colorOrangeTint30')).to('srgb').toString(),
    colorOrangeTint40: baseOrange.set(deltas.get('colorOrangeTint40')).to('srgb').toString(),
    colorOrangeTint50: baseOrange.set(deltas.get('colorOrangeTint50')).to('srgb').toString(),
    colorOrangeTint60: baseOrange.set(deltas.get('colorOrangeTint60')).to('srgb').toString(),
    colorOrangeTint70: baseOrange.set(deltas.get('colorOrangeTint70')).to('srgb').toString(),
    colorOrangeTint80: baseOrange.set(deltas.get('colorOrangeTint80')).to('srgb').toString(),
    colorOrangeTint90: baseOrange.set(deltas.get('colorOrangeTint90')).to('srgb').toString(),
    colorOrangeTint95: baseOrange.set(deltas.get('colorOrangeTint95')).to('srgb').toString(),

    colorYellow5: baseYellow.set(deltas.get('colorYellow5')).to('srgb').toString(),
    colorYellow10: baseYellow.set(deltas.get('colorYellow10')).to('srgb').toString(),
    colorYellow20: baseYellow.set(deltas.get('colorYellow20')).to('srgb').toString(),
    colorYellow30: baseYellow.set(deltas.get('colorYellow30')).to('srgb').toString(),
    colorYellow40: baseYellow.set(deltas.get('colorYellow40')).to('srgb').toString(),
    colorYellow50: colorYellow,
    colorYellow60: baseYellow.set(deltas.get('colorYellow60')).to('srgb').toString(),
    colorYellow70: baseYellow.set(deltas.get('colorYellow70')).to('srgb').toString(),
    colorYellow80: baseYellow.set(deltas.get('colorYellow80')).to('srgb').toString(),
    colorYellow90: baseYellow.set(deltas.get('colorYellow90')).to('srgb').toString(),
    colorYellow95: baseYellow.set(deltas.get('colorYellow95')).to('srgb').toString(),

    colorYellowTint5: baseYellow.set(deltas.get('colorYellowTint5')).to('srgb').toString(),
    colorYellowTint10: baseYellow.set(deltas.get('colorYellowTint10')).to('srgb').toString(),
    colorYellowTint20: baseYellow.set(deltas.get('colorYellowTint20')).to('srgb').toString(),
    colorYellowTint30: baseYellow.set(deltas.get('colorYellowTint30')).to('srgb').toString(),
    colorYellowTint40: baseYellow.set(deltas.get('colorYellowTint40')).to('srgb').toString(),
    colorYellowTint50: baseYellow.set(deltas.get('colorYellowTint50')).to('srgb').toString(),
    colorYellowTint60: baseYellow.set(deltas.get('colorYellowTint60')).to('srgb').toString(),
    colorYellowTint70: baseYellow.set(deltas.get('colorYellowTint70')).to('srgb').toString(),
    colorYellowTint80: baseYellow.set(deltas.get('colorYellowTint80')).to('srgb').toString(),
    colorYellowTint90: baseYellow.set(deltas.get('colorYellowTint90')).to('srgb').toString(),
    colorYellowTint95: baseYellow.set(deltas.get('colorYellowTint95')).to('srgb').toString(),

    colorGreen5: baseGreen.set(deltas.get('colorGreen5')).to('srgb').toString(),
    colorGreen10: baseGreen.set(deltas.get('colorGreen10')).to('srgb').toString(),
    colorGreen20: baseGreen.set(deltas.get('colorGreen20')).to('srgb').toString(),
    colorGreen30: baseGreen.set(deltas.get('colorGreen30')).to('srgb').toString(),
    colorGreen40: baseGreen.set(deltas.get('colorGreen40')).to('srgb').toString(),
    colorGreen50: colorGreen,
    colorGreen60: baseGreen.set(deltas.get('colorGreen60')).to('srgb').toString(),
    colorGreen70: baseGreen.set(deltas.get('colorGreen70')).to('srgb').toString(),
    colorGreen80: baseGreen.set(deltas.get('colorGreen80')).to('srgb').toString(),
    colorGreen90: baseGreen.set(deltas.get('colorGreen90')).to('srgb').toString(),
    colorGreen95: baseGreen.set(deltas.get('colorGreen95')).to('srgb').toString(),

    colorGreenTint5: baseGreen.set(deltas.get('colorGreenTint5')).to('srgb').toString(),
    colorGreenTint10: baseGreen.set(deltas.get('colorGreenTint10')).to('srgb').toString(),
    colorGreenTint20: baseGreen.set(deltas.get('colorGreenTint20')).to('srgb').toString(),
    colorGreenTint30: baseGreen.set(deltas.get('colorGreenTint30')).to('srgb').toString(),
    colorGreenTint40: baseGreen.set(deltas.get('colorGreenTint40')).to('srgb').toString(),
    colorGreenTint50: baseGreen.set(deltas.get('colorGreenTint50')).to('srgb').toString(),
    colorGreenTint60: baseGreen.set(deltas.get('colorGreenTint60')).to('srgb').toString(),
    colorGreenTint70: baseGreen.set(deltas.get('colorGreenTint70')).to('srgb').toString(),
    colorGreenTint80: baseGreen.set(deltas.get('colorGreenTint80')).to('srgb').toString(),
    colorGreenTint90: baseGreen.set(deltas.get('colorGreenTint90')).to('srgb').toString(),
    colorGreenTint95: baseGreen.set(deltas.get('colorGreenTint95')).to('srgb').toString(),

    colorRainbow0: colorBlue,
    colorRainbow1: colorGreen,
    colorRainbow2: baseGreen.set(deltas.get('colorRainbow2')).to('srgb').toString(),
    colorRainbow3: colorYellow,
    colorRainbow4: colorOrange,
    colorRainbow5: baseOrange.set(deltas.get('colorRainbow5')).to('srgb').toString(),
    colorRainbow6: colorRed,
    colorRainbow7: baseRed.set(deltas.get('colorRainbow7')).to('srgb').toString(),
    colorRainbow8: colorPink,
    colorRainbow9: basePink.set(deltas.get('colorRainbow7')).to('srgb').toString(),
    colorRainbow10: colorPurple
  };
};
*/
