import { getCustomTokens } from './get_custom_tokens.js';

export const getSemanticTokens = (colors) => {
  const customTokens = getCustomTokens(colors);
  const staticTokens = getCustomTokens({
    black: '0, 0, 0',
    white: '255, 255, 255',
    gray: '128, 128, 128',

    red: '255, 73, 48',
    green: '0, 207, 53',
    purple: '124, 92, 255'
  });

  return {
    chrome: customTokens.colorNavy,
    'chrome-panel': customTokens.colorNavy95,
    'chrome-panel-border': customTokens.colorWhiteOnDarkTint5,
    'chrome-tint': customTokens.colorWhiteOnDarkTint5,
    'chrome-tint-strong': customTokens.colorWhiteOnDarkTint10,
    'chrome-tint-heavy': customTokens.colorWhiteOnDarkTint15,
    'chrome-mobile': customTokens.colorNavy,
    'chrome-fg': customTokens.colorWhiteOnDark,
    'chrome-fg-secondary': customTokens.colorNavy40,
    'chrome-fg-tertiary': customTokens.colorNavy60,

    accent: customTokens.colorAccent,
    'accent-fg': customTokens.colorBlack,
    'accent-fg-light': customTokens.colorWhite,
    'accent-hover': customTokens.colorAccent40,
    'accent-pressed': customTokens.colorAccent30,
    'accent-tint': customTokens.colorAccentTint10,
    'accent-tint-strong': customTokens.colorAccentTint20,
    'accent-tint-heavy': customTokens.colorAccentTint30,

    'content-panel': customTokens.colorWhite,
    'content-panel-border': customTokens.colorTransparent,
    'content-tint': customTokens.colorNavyTint5,
    'content-tint-strong': customTokens.colorNavyTint10,
    'content-tint-heavy': customTokens.colorNavyTint15,
    'content-mobile-container': customTokens.colorNavy3,
    'content-fg': customTokens.colorBlack,
    'content-fg-secondary': customTokens.colorNavy60,
    'content-fg-tertiary': customTokens.colorNavy40,

    'color-panel-border': customTokens.colorTransparent,
    'color-tint': staticTokens.colorBlackTint10,
    'color-tint-strong': staticTokens.colorBlackTint15,
    'color-tint-heavy': staticTokens.colorBlackTint20,
    'color-fg': staticTokens.colorBlack,
    'color-fg-secondary': staticTokens.colorBlackTint80,
    'color-fg-tertiary': staticTokens.colorBlackTint60,
    'color-fg-light': staticTokens.colorWhite,
    'color-fg-light-secondary': staticTokens.colorWhiteTint80,
    'color-fg-light-tertiary': staticTokens.colorWhiteTint60,

    'image-bg': staticTokens.colorBlack,
    'image-panel-border': customTokens.colorWhiteTint10,
    'image-tint': staticTokens.colorBlackTint40,
    'image-tint-strong': staticTokens.colorBlackTint50,
    'image-tint-heavy': staticTokens.colorBlackTint60,
    'image-fg': staticTokens.colorWhite,
    'image-fg-secondary': staticTokens.colorWhiteTint80,
    'image-fg-tertiary': staticTokens.colorWhiteTint60,

    'side-menu': customTokens.colorNavy,
    'side-menu-shadow': customTokens.colorWhiteTint10,
    'top-menu': customTokens.colorNavy,
    'top-menu-shadow': customTokens.colorWhiteTint10,
    modal: customTokens.colorWhite,
    'modal-border': customTokens.colorNavyTint10,
    'tool-tip': customTokens.colorBlack,
    'tool-tip-text': customTokens.colorWhite,
    'overlay-tint': customTokens.colorNavyTint20,
    'overlay-tint-strong': customTokens.colorNavyTint60,
    'overlay-tint-heavy': customTokens.colorNavyTint80,
    'unread-tint': customTokens.colorBlueTint10,
    'unread-tint-hover': customTokens.colorBlueTint20,
    'badge-text': staticTokens.colorBlack,
    'badge-icon': staticTokens.colorWhite,

    'chrome-ui': customTokens.colorBlue,
    'chrome-ui-hover': customTokens.colorBlue40,
    'chrome-ui-pressed': customTokens.colorBlue30,
    'chrome-ui-focus': customTokens.colorBlue,
    'chrome-ui-fg': customTokens.colorBlack,
    'chrome-ui-fg-secondary': customTokens.colorBlackTint80,
    'chrome-ui-fg-tertiary': customTokens.colorBlackTint60,
    'chrome-ui-toggle': staticTokens.colorWhite,
    'chrome-danger': staticTokens.colorRed30,
    'chrome-success': staticTokens.colorGreen30,
    'chrome-education': staticTokens.colorPurple30,
    'chrome-blue': customTokens.colorBlue30,
    'chrome-purple': customTokens.colorPurple30,
    'chrome-pink': customTokens.colorPink30,
    'chrome-red': customTokens.colorRed30,
    'chrome-orange': customTokens.colorOrange30,
    'chrome-yellow': customTokens.colorYellow30,
    'chrome-green': customTokens.colorGreen30,

    'content-ui': customTokens.colorNavy,
    'content-ui-hover': customTokens.colorNavy90,
    'content-ui-pressed': customTokens.colorNavy80,
    'content-ui-focus': customTokens.colorBlue,
    'content-ui-fg': customTokens.colorWhite,
    'content-ui-fg-secondary': customTokens.colorNavy40,
    'content-ui-fg-tertiary': customTokens.colorNavy60,
    'content-ui-toggle': staticTokens.colorWhite,
    'content-danger': staticTokens.colorRed70,
    'content-success': staticTokens.colorGreen70,
    'content-education': staticTokens.colorPurple70,
    'content-blue': customTokens.colorBlue70,
    'content-purple': customTokens.colorPurple70,
    'content-pink': customTokens.colorPink70,
    'content-red': customTokens.colorRed70,
    'content-orange': customTokens.colorOrange70,
    'content-yellow': customTokens.colorYellow70,
    'content-green': customTokens.colorGreen70,

    'color-ui': staticTokens.colorBlack,
    'color-ui-hover': staticTokens.colorBlackTint90,
    'color-ui-pressed': staticTokens.colorBlackTint80,
    'color-ui-focus': staticTokens.colorBlack,
    'color-ui-fg': staticTokens.colorWhite,
    'color-ui-fg-secondary': staticTokens.colorGray40,
    'color-ui-fg-tertiary': staticTokens.colorGray60,
    'color-ui-toggle': staticTokens.colorWhite,

    'image-ui': staticTokens.colorWhite,
    'image-ui-hover': staticTokens.colorWhiteTint90,
    'image-ui-pressed': staticTokens.colorWhiteTint80,
    'image-ui-accent': staticTokens.colorWhite,
    'image-ui-fg': staticTokens.colorBlack,
    'image-ui-fg-secondary': customTokens.colorNavy60,
    'image-ui-fg-tertiary': customTokens.colorNavy40,
    'image-ui-toggle': staticTokens.colorWhite,

    danger: staticTokens.colorRed,
    'danger-hover': staticTokens.colorRed60,
    'danger-pressed': staticTokens.colorRed70,
    'danger-tint': staticTokens.colorRedTint10,
    'danger-tint-strong': staticTokens.colorRedTint20,
    'danger-tint-heavy': staticTokens.colorRedTint30,
    success: staticTokens.colorGreen,
    'success-hover': staticTokens.colorGreen40,
    'success-pressed': staticTokens.colorGreen30,
    'success-tint': staticTokens.colorGreenTint10,
    'success-tint-strong': staticTokens.colorGreenTint20,
    'success-tint-heavy': staticTokens.colorGreenTint30,
    education: staticTokens.colorPurple,
    'education-hover': staticTokens.colorPurple40,
    'education-pressed': staticTokens.colorPurple30,
    'education-tint': staticTokens.colorPurpleTint10,
    'education-tint-strong': staticTokens.colorPurpleTint20,
    'education-tint-heavy': staticTokens.colorPurpleTint30,

    'brand-blue': customTokens.colorBlue,
    'brand-blue-hover': customTokens.colorBlue40,
    'brand-blue-pressed': customTokens.colorBlue30,
    'brand-blue-tint': customTokens.colorBlueTint10,
    'brand-blue-tint-strong': customTokens.colorBlueTint20,
    'brand-blue-tint-heavy': customTokens.colorBlueTint30,
    'brand-purple': customTokens.colorPurple,
    'brand-purple-hover': customTokens.colorPurple40,
    'brand-purple-pressed': customTokens.colorPurple30,
    'brand-purple-tint': customTokens.colorPurpleTint10,
    'brand-purple-tint-strong': customTokens.colorPurpleTint20,
    'brand-purple-tint-heavy': customTokens.colorPurpleTint30,
    'brand-pink': customTokens.colorPink,
    'brand-pink-hover': customTokens.colorPink40,
    'brand-pink-pressed': customTokens.colorPink30,
    'brand-pink-tint': customTokens.colorPinkTint10,
    'brand-pink-tint-strong': customTokens.colorPinkTint20,
    'brand-pink-tint-heavy': customTokens.colorPinkTint30,
    'brand-red': customTokens.colorRed,
    'brand-red-hover': customTokens.colorRed40,
    'brand-red-pressed': customTokens.colorRed30,
    'brand-red-tint': customTokens.colorRedTint10,
    'brand-red-tint-strong': customTokens.colorRedTint20,
    'brand-red-tint-heavy': customTokens.colorRedTint30,
    'brand-orange': customTokens.colorOrange,
    'brand-orange-hover': customTokens.colorOrange40,
    'brand-orange-pressed': customTokens.colorOrange30,
    'brand-orange-tint': customTokens.colorOrangeTint10,
    'brand-orange-tint-strong': customTokens.colorOrangeTint20,
    'brand-orange-tint-heavy': customTokens.colorOrangeTint30,
    'brand-yellow': customTokens.colorYellow,
    'brand-yellow-hover': customTokens.colorYellow40,
    'brand-yellow-pressed': customTokens.colorYellow30,
    'brand-yellow-tint': customTokens.colorYellowTint10,
    'brand-yellow-tint-strong': customTokens.colorYellowTint20,
    'brand-yellow-tint-heavy': customTokens.colorYellowTint30,
    'brand-green': customTokens.colorGreen,
    'brand-green-hover': customTokens.colorGreen40,
    'brand-green-pressed': customTokens.colorGreen30,
    'brand-green-tint': customTokens.colorGreenTint10,
    'brand-green-tint-strong': customTokens.colorGreenTint20,
    'brand-green-tint-heavy': customTokens.colorGreenTint30
  };
};
