import { getCustomTokens } from './get_custom_tokens';

export const getSemanticTokens = (colors) => {
  const customTokens = getCustomTokens(colors);

  return {
    chrome: customTokens.colorNavy,
    'chrome-panel': customTokens.colorNavy95,
    'chrome-panel-border': customTokens.colorWhiteOnDarkTint5,
    'chrome-tint': customTokens.colorWhiteOnDarkTint5,
    'chrome-tint-strong': customTokens.colorWhiteOnDarkTint10,
    'chrome-tint-heavy': customTokens.colorWhiteOnDarkTint15,
    'chrome-mobile': customTokens.colorNavy,
    'chrome-fg': customTokens.colorWhiteOnDark,
    'chrome-fg-secondary': customTokens.colorNavy40,
    'chrome-fg-tertiary': customTokens.colorNavy60,

    accent: customTokens.colorAccent,
    'accent-fg': customTokens.colorBlack,
    'accent-fg-light': customTokens.colorWhite,
    'accent-hover': customTokens.colorAccent40,
    'accent-pressed': customTokens.colorAccent30,
    'accent-tint': customTokens.colorAccentTint10,
    'accent-tint-strong': customTokens.colorAccentTint20,
    'accent-tint-heavy': customTokens.colorAccentTint30,

    'content-panel': customTokens.colorWhite,
    'content-panel-border': customTokens.colorTransparent,
    'content-tint': customTokens.colorNavyTint5,
    'content-tint-strong': customTokens.colorNavyTint10,
    'content-tint-heavy': customTokens.colorNavyTint15,
    'content-mobile-container': customTokens.colorNavy3,
    'content-fg': customTokens.colorBlack,
    'content-fg-secondary': customTokens.colorNavy60,
    'content-fg-tertiary': customTokens.colorNavy40,

    'color-panel-border': customTokens.colorTransparent,

    'image-panel-border': customTokens.colorWhiteTint10,
    'image-tint': customTokens.colorBlackTint40,
    'image-tint-strong': customTokens.colorBlackTint50,
    'image-tint-heavy': customTokens.colorBlackTint60,

    'side-menu': customTokens.colorNavy,
    'side-menu-shadow': customTokens.colorWhiteTint10,
    'top-menu': customTokens.colorNavy,
    'top-menu-shadow': customTokens.colorWhiteTint10,
    modal: customTokens.colorWhite,
    'modal-border': customTokens.colorNavyTint10,
    'tool-tip': customTokens.colorBlack,
    'tool-tip-text': customTokens.colorWhite,
    'overlay-tint': customTokens.colorNavyTint20,
    'overlay-tint-strong': customTokens.colorNavyTint60,
    'overlay-tint-heavy': customTokens.colorNavyTint80,
    'unread-tint': customTokens.colorBlueTint10,
    'unread-tint-hover': customTokens.colorBlueTint20,
    'badge-text': customTokens.colorBlack,

    'chrome-ui': customTokens.colorBlue,
    'chrome-ui-hover': customTokens.colorBlue40,
    'chrome-ui-pressed': customTokens.colorBlue30,
    'chrome-ui-focus': customTokens.colorBlue,
    'chrome-ui-fg': customTokens.colorBlack,
    'chrome-ui-fg-secondary': customTokens.colorBlackTint80,
    'chrome-ui-fg-tertiary': customTokens.colorBlackTint60,
    'chrome-danger': customTokens.colorRed30,
    'chrome-success': customTokens.colorGreen30,
    'chrome-education': customTokens.colorPurple30,
    'chrome-blue': customTokens.colorBlue30,
    'chrome-purple': customTokens.colorPurple30,
    'chrome-pink': customTokens.colorPink30,
    'chrome-red': customTokens.colorRed30,
    'chrome-orange': customTokens.colorOrange30,
    'chrome-yellow': customTokens.colorYellow30,
    'chrome-green': customTokens.colorGreen30,

    'content-ui': customTokens.colorNavy,
    'content-ui-hover': customTokens.colorNavy90,
    'content-ui-pressed': customTokens.colorNavy80,
    'content-ui-focus': customTokens.colorBlue,
    'content-ui-fg': customTokens.colorWhite,
    'content-ui-fg-secondary': customTokens.colorNavy40,
    'content-ui-fg-tertiary': customTokens.colorNavy60,
    'content-danger': customTokens.colorRed70,
    'content-success': customTokens.colorGreen70,
    'content-education': customTokens.colorPurple70,
    'content-blue': customTokens.colorBlue70,
    'content-purple': customTokens.colorPurple70,
    'content-pink': customTokens.colorPink70,
    'content-red': customTokens.colorRed70,
    'content-orange': customTokens.colorOrange70,
    'content-yellow': customTokens.colorYellow70,
    'content-green': customTokens.colorGreen70,

    'color-ui-fg-secondary': customTokens.colorGray40,
    'color-ui-fg-tertiary': customTokens.colorGray60,

    'image-ui-fg-secondary': customTokens.colorNavy60,
    'image-ui-fg-tertiary': customTokens.colorNavy40,

    'danger-hover': customTokens.colorRed60,
    'danger-pressed': customTokens.colorRed70,

    'brand-blue': customTokens.colorBlue,
    'brand-blue-hover': customTokens.colorBlue40,
    'brand-blue-pressed': customTokens.colorBlue30,
    'brand-blue-tint': customTokens.colorBlueTint10,
    'brand-blue-tint-strong': customTokens.colorBlueTint20,
    'brand-blue-tint-heavy': customTokens.colorBlueTint30,
    'brand-purple': customTokens.colorPurple,
    'brand-purple-hover': customTokens.colorPurple40,
    'brand-purple-pressed': customTokens.colorPurple30,
    'brand-purple-tint': customTokens.colorPurpleTint10,
    'brand-purple-tint-strong': customTokens.colorPurpleTint20,
    'brand-purple-tint-heavy': customTokens.colorPurpleTint30,
    'brand-pink': customTokens.colorPink,
    'brand-pink-hover': customTokens.colorPink40,
    'brand-pink-pressed': customTokens.colorPink30,
    'brand-pink-tint': customTokens.colorPinkTint10,
    'brand-pink-tint-strong': customTokens.colorPinkTint20,
    'brand-pink-tint-heavy': customTokens.colorPinkTint30,
    'brand-red': customTokens.colorRed,
    'brand-red-hover': customTokens.colorRed40,
    'brand-red-pressed': customTokens.colorRed30,
    'brand-red-tint': customTokens.colorRedTint10,
    'brand-red-tint-strong': customTokens.colorRedTint20,
    'brand-red-tint-heavy': customTokens.colorRedTint30,
    'brand-orange': customTokens.colorOrange,
    'brand-orange-hover': customTokens.colorOrange40,
    'brand-orange-pressed': customTokens.colorOrange30,
    'brand-orange-tint': customTokens.colorOrangeTint10,
    'brand-orange-tint-strong': customTokens.colorOrangeTint20,
    'brand-orange-tint-heavy': customTokens.colorOrangeTint30,
    'brand-yellow': customTokens.colorYellow,
    'brand-yellow-hover': customTokens.colorYellow40,
    'brand-yellow-pressed': customTokens.colorYellow30,
    'brand-yellow-tint': customTokens.colorYellowTint10,
    'brand-yellow-tint-strong': customTokens.colorYellowTint20,
    'brand-yellow-tint-heavy': customTokens.colorYellowTint30,
    'brand-green': customTokens.colorGreen,
    'brand-green-hover': customTokens.colorGreen40,
    'brand-green-pressed': customTokens.colorGreen30,
    'brand-green-tint': customTokens.colorGreenTint10,
    'brand-green-tint-strong': customTokens.colorGreenTint20,
    'brand-green-tint-heavy': customTokens.colorGreenTint30
  };
};
