name: Release Notes

on: workflow_dispatch

permissions:
  contents: read

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          cache: true

      - name: Generate release notes
        run: deno run release-notes >> $GITHUB_STEP_SUMMARY
        env:
          GITHUB_API_URL: ${{ github.api_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
