name: Update Palette Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # monthly

permissions:
  contents: write
  pull-requests: write

jobs:
  update-palette-data:
    name: Update Palette Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Run update script
        run: dev/update-palette-data.js

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: 'chore: update palette data'
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          branch: automatic-palette-data-update
          title: 'chore: update palette data'
          body: |
            Updates the palette data for Tumblr's native palettes.
            <sub>This pull request is autogenerated by the "Update Palette Data" GitHub action.</sub>
